"""Fetch the Oxford Great Parchment text (Bodleian MS Hunt. Add. E) from the Ilanot Portal.

usage: py -3.13 fetch_oxford.py
Writes oxford/shapes.json (the portal's raw response) and oxford/oxford_zones.md
(one section per zone: zone label, Ilanot shape id, plain Hebrew text), sorted by zone.

The portal's viewer loads every zone's transcription in a single request:
    https://www.ilanot.org/shapesjson?id=https://ilanot.org/resource/item/manuscript40rgm
The response is a list with one surface; `[0]["text"][<shape id>]` has `zoneName` and `text`
(XHTML). Zones 2.1-2.22 hold the running text of the narratives that Tzarfati expounds.
A zone link is https://www.ilanot.org/detail?id=https://ilanot.org/resource/item/manuscript40rgm&shape=<shape id>
"""
import html, json, re, urllib.request
from pathlib import Path

URL = "https://www.ilanot.org/shapesjson?id=https://ilanot.org/resource/item/manuscript40rgm"
OUT = Path(__file__).resolve().parent / "oxford"


def plain(xhtml):
    return " ".join(html.unescape(re.sub(r"<[^>]+>", " ", xhtml or "")).split())


def zone_key(label):
    return [int(p) for p in label.split(".") if p.isdigit()]


def main():
    OUT.mkdir(exist_ok=True)
    raw = urllib.request.urlopen(urllib.request.Request(URL, headers={"User-Agent": "yeriah_ms"}), timeout=60).read()
    (OUT / "shapes.json").write_bytes(raw)
    zones = [(z["zoneName"], z["svgId"], plain(z["text"])) for z in json.loads(raw)[0]["text"].values()]
    zones = sorted((z for z in zones if z[2]), key=lambda z: zone_key(z[0]))
    lines = ["# Oxford Great Parchment: zone texts from the Ilanot Portal", "",
             f"Source: {URL}", "Generated by `fetch_oxford.py`. Do not edit by hand.", ""]
    for label, sid, text in zones:
        lines += [f"## Zone {label} | {sid}", text, ""]
    (OUT / "oxford_zones.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(zones)} zones to {OUT}")


if __name__ == "__main__":
    main()
